"""Robot Framework keyword library for the documentation screenshot capture suite.

Reads docs/screenshot-manifest.json (generated by docs/scripts/build-site.js from the
```screenshot blocks in docs/business/**/*.md) and gives the .robot suite the list of
shots to take. Each manifest entry is either:

  - "navigable": has a url_pattern and no actions — captured by plain navigation, or
  - "interactive": has an `actions` list (declared in the .md block itself) — captured
    by replaying each declared UI action (open the App Launcher, type a search, click
    New, fill a field, ...) so the image depicts the exact step it documents.

Keeping this logic in Python keeps the .robot files readable.
"""
import json
import os
import re
from urllib.parse import urlparse

from robot.api.deco import keyword, library


@library(scope="GLOBAL")
class DocsCapture:
    ROBOT_LIBRARY_VERSION = "2.0"

    def __init__(self):
        here = os.path.dirname(os.path.abspath(__file__))
        # resources -> DocsProject -> robot -> capture -> docs -> <repo root>
        self.repo_root = os.path.abspath(os.path.join(here, "..", "..", "..", "..", ".."))
        self.manifest_path = os.path.join(self.repo_root, "docs", "screenshot-manifest.json")
        self.images_dir = os.path.join(self.repo_root, "docs", "images")

    @keyword
    def load_manifest(self):
        """Return the full list of screenshot entries from docs/screenshot-manifest.json."""
        with open(self.manifest_path, encoding="utf-8") as fh:
            return json.load(fh)

    @keyword
    def navigable_screenshots(self):
        """Entries captured by navigating to url_pattern (no declared actions)."""
        return [
            s for s in self.load_manifest()
            if s.get("url_pattern") and not s.get("actions")
        ]

    @keyword
    def interactive_screenshots(self):
        """Entries with a declared `actions` list — replayed step by step."""
        return [s for s in self.load_manifest() if s.get("actions")]

    @keyword
    def normalized_actions(self, shot):
        """Normalize a shot's `actions` list into uniform dicts for the .robot dispatcher.

        Accepted forms in the markdown block:
          - "click_new"                                (bare verb)
          - {"search_app_launcher": "Orders"}          (verb: argument)
          - {"fill_field": {"field": "Name", "value": "Acme"}}   (verb: mapping)

        Every returned dict has all of: verb, arg, field, value (strings, "" if unused),
        so the Robot side can index them without existence checks.
        """
        out = []
        for item in shot.get("actions") or []:
            verb, arg, field, value = "", "", "", ""
            if isinstance(item, str):
                verb = item.strip()
            elif isinstance(item, dict) and len(item) == 1:
                verb, payload = next(iter(item.items()))
                verb = str(verb).strip()
                if isinstance(payload, dict):
                    field = str(payload.get("field", "") or "")
                    value = str(payload.get("value", "") or "")
                elif payload is not None:
                    arg = str(payload)
            if verb:
                out.append({"verb": verb, "arg": arg, "field": field, "value": value})
        return out

    @keyword
    def images_dir_path(self):
        """Absolute path to docs/images/ (created if missing)."""
        os.makedirs(self.images_dir, exist_ok=True)
        return self.images_dir

    @keyword
    def screenshot_exists(self, screenshot_id):
        """True if docs/images/<screenshot_id>.png already exists."""
        return os.path.exists(os.path.join(self.images_dir, f"{screenshot_id}.png"))

    @keyword
    def object_api_name(self, url_pattern):
        """Pull the object API name out of a /lightning/r/<Object>/{recordId}/... pattern."""
        m = re.search(r"/lightning/r/([^/]+)/", url_pattern or "")
        return m.group(1) if m else ""

    @keyword
    def origin_of(self, url):
        """Return scheme://host for a full URL (used to derive the org base URL)."""
        p = urlparse(url)
        return f"{p.scheme}://{p.netloc}"
